SELECT P.ID, P.NOME, NVL(F1.DESCRICAO, '----') FUNCAO, NVL(F2.DESCRICAO, '------') DEPARTAMENTO, H.NOME HORARIO, E.NOME FROM 
PESSOAS P LEFT JOIN FILTRO1 F1 ON F1.ID = P.FILTRO1_ID LEFT JOIN FILTRO2 F2 ON F2.ID = P.FILTRO2_ID JOIN HORARIOS H ON H.ID = P.HORARIO_ID
JOIN EMPRESAS E ON P.EMPRESA_ID = E.ID