CREATE OR REPLACE PROCEDURE CADASTRA_PESSOAS 
(
  QUANTIDADE IN NUMBER DEFAULT 100 
) AS
V_COUNT INTEGER;
V_ID_OCUPADO PESSOAS.N_IDENTIFICADOR%TYPE;
V_ID INTEGER;
CURSOR MEU_CURSOR IS SELECT N_IDENTIFICADOR FROM PESSOAS;
BEGIN
  V_COUNT := 1;
  V_ID := 1;
  WHILE V_COUNT < QUANTIDADE+1 LOOP
     OPEN MEU_CURSOR;
     LOOP
        FETCH MEU_CURSOR INTO V_ID_OCUPADO;
        IF MEU_CURSOR%NOTFOUND THEN
           INSERT INTO PESSOAS(N_IDENTIFICADOR, NOME, EMPRESA_ID, HORARIO_ID, ESTADO, CLASSIFICACAO_ID, CRIACAO_USU_ID, CRIACAO_DATA) 
           VALUES(V_ID, 'DOUGLAS ' || V_ID, 1, 1, 0, 1, 1, SYSDATE );
           V_ID := V_ID + 1;
           V_COUNT := V_COUNT + 1;
           DBMS_OUTPUT.PUT_LINE('INSERT..' || V_ID);
           EXIT;
        END IF;
        IF V_ID = V_ID_OCUPADO THEN
           DBMS_OUTPUT.PUT_LINE('ID..' || V_ID_OCUPADO || '..OCUPADO');
           V_ID := V_ID + 1;
           EXIT;
        ELSE
           CONTINUE;
        END IF;
    END LOOP;
         CLOSE MEU_CURSOR;
  END LOOP;
END CADASTRA_PESSOAS;