--ATIVA A SAIDA NA TELA
SET SERVEROUTPUT ON 
/
--AJUSTA O CABEÇALHO DA COLUNA ALINHADA A ESQUERDA
col id just center
/
--FORMATA A COLUNA(CABEÇALHO + RECORDS) COM 50 CARACTERES DE LIMITE
col nome format A3 
/
--FORMATA O VALOR DA COLUNA COM QUEBRA DE LINHA COM PALAVRAS INTEIRAS QUANDO POSSÍVEL
col nome wor 
/
--TAMANHO DA PAGINA VERITICAL COM 100 LINHAS ATÉ EXIBIR O CABEÇALHO NOVAMENTE
set pagesize 100 
/
--QUANTIDADES DE CARACTERES HORIZONTAL ATÉ QUEBRAR A LINHA
set linesize 100
/
--LIMPA A FORMATAÇÂO DAS COLUNAS
clear columns
/
--AJUDA SQLPLUS, EXIBE TODAS AS OPÇÔES
help index
/
--AJUDA PARA UM OPÇÂO ESPECIFICA
help column
/