SELECT COUNT(1) ACESSOS, C.DESCRICAO CLASSIFICACAO FROM EVENTOS_ACESSOS E JOIN PESSOAS P ON E.PESSOA_ID = P.ID JOIN 
CLASSIFICACOES C ON C.ID = P.CLASSIFICACAO_ID
GROUP BY C.DESCRICAO, P.CLASSIFICACAO_ID HAVING P.CLASSIFICACAO_ID = 1 
