ALTER TABLE PESSOAS ADD TOTAL_REFEICOES NUMBER(10);

CREATE OR REPLACE TRIGGER ATUALIZA_TOTAL_REFEICOES 
AFTER INSERT OR UPDATE OF VALOR_REFEICAO OR DELETE ON EVENTOS_ACESSOS
FOR EACH ROW
BEGIN
IF INSERTING THEN
  UPDATE PESSOAS SET TOTAL_REFEICOES = NVL(TOTAL_REFEICOES,0) + :NEW.VALOR_REFEICAO WHERE ID = :NEW.PESSOA_ID;
ELSIF UPDATING THEN
  UPDATE PESSOAS SET TOTAL_REFEICOES = NVL(TOTAL_REFEICOES,0) + :NEW.VALOR_REFEICAO - :OLD.VALOR_REFEICAO WHERE ID = :NEW.PESSOA_ID;
ELSIF DELETING THEN
  UPDATE PESSOAS SET TOTAL_REFEICOES = NVL(TOTAL_REFEICOES,0) - :OLD.VALOR_REFEICAO WHERE ID = :OLD.PESSOA_ID;
END IF;
END;
