CREATE VIEW MINHA_VIEW_EQUIPAMENTOS
AS
SELECT P.NOME AS 'NOME DA PESSOA', COUNT(EA.ID) AS 'QUANTIDADE DE ACESSOS', PN.N_IDENTIFICADOR AS 'NÚMERO IDENTIFICADOR DA PESSOA', 
EM.NOME AS 'NOME DA EMPRESA', CL.DESCRICAO AS 'CLASSIFICAÇÃO'
FROM EVENTOS_ACESSOS EA
JOIN PESSOAS P ON P.ID = EA.PESSOA_ID
JOIN PESSOAS PN ON PN.N_IDENTIFICADOR = EA.PESSOA_ID
JOIN EMPRESAS EM ON EM.ID= P.EMPRESA_ID
JOIN CLASSIFICACOES CL ON CL.ID = P.CLASSIFICACAO_ID GROUP BY P.NOME, PN.N_IDENTIFICADOR, EM.NOME, CL.DESCRICAO